### ISSUE TITLE
multi language support

### ISSUE THREAD

**Issue by erroronline1** [Mightyfrong/gallifreyan-translation-helper#15]
include english, lithuanian, german, ask community for help later on. (i already have a good language model that could be implemented)

**Comment by ModisR** [comment]
Whether a system supports non-English characters is entirely up to its designer, no?

You thinking of unofficially extending those which don't have all the chars?

**Comment by erroronline1** [comment]
it was not about adding unofficial characters. i followed your idea of a multi language user interface to reach a wider audience.

**Comment by ModisR** [comment]
I do feel it would make sense to hold off on the Lithuanian, except perhaps for Cot as none of the systems  have ways to transcrib the whole Lithuanian alphabet.

**Comment by erroronline1** [comment]
wait, that was your idea in the first place 😂. it's just about the interface. but you can simply comment lithunian out of the registered properties if you're feeling uncomfortable 🤷

**Comment by ModisR** [comment]
I was just spitballing. Hadn't considered the level of support for Lithuanian letters at the time. Anyway, no big deal.
