### ISSUE TITLE
colorpicker

### ISSUE THREAD

**Issue by erroronline1** [Mightyfrong/gallifreyan-translation-helper#16]
* add colorpicker for background and foreground <input type="color"
* read input as global property and implement it in every module
* fill canvas with background color (currently transparent) -> this will need the assignment of width and height in every module by calling a global function to avoid adding fillRect everytime

**Comment by ModisR** [comment]
I don't think the first point make sense. This is a tool for Gallifreyan scribes, not budding web designers.

The others may be a good idea, though. Having the translator output fit in with the style of the rest of the site could be nice.

**Comment by erroronline1** [comment]
all was meant to have the canvas blend into the sites design in the first place. but you never know if someone finds it hard to read so i added customizable colors. thats all.
