### ISSUE TITLE
Refine Sherman's Artwork

### ISSUE THREAD

**Issue by ModisR** [Mightyfrong/gallifreyan-translation-helper#19]
* Fix caption kerning (some letters overlap)
* Tidy up line ends (so they don't stick out of corners)
* Arrange words, not just letters, in circles
* Come up with algo for joining line decos

**Comment by erroronline1** [comment]
are you on that task since you assigned yourself? was planning to transfer canvas to svg on friday, unless you already have an approach.

**Comment by ModisR** [comment]
SVG migration is a separate task to this. That task, yes, I had planned to do myself but you can join in, if you like. I'm currently focused on making it work for TARDIS so you can do it for Sherman's if you like.

**Comment by ModisR** [comment]
@erroronline1, I'll go ahead and write the new issue and assign it to you to make things formal.

**Comment by erroronline1** [comment]
i fixed kerning. and last week i tried to tidy up line ends, but this is not very satisfactory. a bit better than before but not perfect but i do not get it better done. partly because of me being not goot with maths, partly because drawing the arc occasionally behaves a bit unexpected.

**Comment by ModisR** [comment]
OK no worries. Every bit of progress is a win. Good job on the kerning. I'll close this and spin off smaller, more specific issues for each bullet point.
