### ISSUE TITLE
Refine TARDIS Console artwork

### ISSUE THREAD

**Issue by ModisR** [Mightyfrong/gallifreyan-translation-helper#20]
1. extend line decos to word boundaries instead of cutting them off abruptly
2. add decorative border with captions

**Comment by erroronline1** [comment]
you could use the new ctx.drawText(text, attributes) function for the second topic :)

**Comment by ModisR** [comment]
Yup, cheers. I appreciate you adding that function.

**Comment by erroronline1** [comment]
rework of the whole module closes this topic. there might still be room for improvements but these have to be addressed otherwise. cheers!
