### ISSUE TITLE
Migrate docs to wiki?

### ISSUE THREAD

**Issue by ModisR** [Mightyfrong/gallifreyan-translation-helper#22]
Our README has become rather bloated and I'm thinking it may be worth organising its contents into wiki articles here, while restricting the README itself to a very basic overview of the project.

Let me know your thoughts, @Mightyfrong, @erroronline1.

**Comment by Mightyfrong** [comment]
I agree

**Comment by erroronline1** [comment]
me too

**Comment by ModisR** [comment]
OK, with that answered, I'll open a new issue setting out the steps for this migration.
