### ISSUE TITLE
resize drawings

### ISSUE THREAD

**Issue by erroronline1** [Mightyfrong/gallifreyan-translation-helper#26]
drawings are displayed quite small but i can not determine why. maybe one of you has an idea.

**Comment by ModisR** [comment]
Is this just for TARDIS Console or for all writing systems?

**Comment by erroronline1** [comment]
this is exactly the weird thing for all types. what i tried so far without success:

- set css min-width and max-width: no change
- set this.width and .height from the SVGRenderingContext *2: adds even more empty space around everything (see inspect element)
- set this.width and .height /2: img now without empty space around it
- this.width and .height /4 clips off half of the image despite viewBox referring to the whole scale

the displayed measurements are always the same. before both of us made the progress yesterday tardis-output always fit the whole screen-with. some odd behaviour due to not longer being inline svg?

while img.width and .height has the same value like the background rect still the displayed plot doesn't fit the <img>-dimensions. i just don't get it.
shermans, cc and dotscript calculate wraps by window.innerWidth, so in theory the img should fit the screen but it just doesn't. and i don't get why css has just no freaking effect.

**Comment by ModisR** [comment]
Oh, you set the `.width` and `.height` directly from the rendering context? Do it directly on the `<img>` element.

**Comment by erroronline1** [comment]
but this will be updated on generation according to calculated dimensions

**Comment by ModisR** [comment]
Will it? I imagined it wouldn't do so but if you tried it then here's another idea:

Say, for example, you want to double the size of your SVG image without changing the coordinates. Then try the following code inside `SVGRenderingContext`:
```js
this.svg.setAttribute('width', 2 * width);
this.svg.setAttribute('height', 2 * height);
this.svg.setAttribute('viewBox', `0 0 ${width} ${height}`);
```
The `viewBox` property should restrict the visible part of the image and allow you to scale up without all that empty space you mentioned.

**Comment by erroronline1** [comment]
istn't this what
```js
export class SVGRenderingContext {
	constructor(width, height) {
		const viewBox = `0 0 ${width} ${height}`;
		this.svg = createSVGElement('svg', {
			viewBox
		});
		this.width = width;
		this.height = height;
```
and
```js
//main.js
function translate(ctx) {
	/*...*/
		img.src = URL.createObjectURL(svg.export(input));
		img.width = svg.width;
		img.height = svg.height;
```
is supposed to do (but doesn't)? with or without scaling...

**Comment by ModisR** [comment]
Ah, no, you see, if you look carefully you'll see only the `<svg>` element's `viewBox` property is being set explicitly but not its `width` or `height`.

The `width` and `height` props of the rendering context are unconnected to the SVG document itself. I just created them to pass to `main.js` for sizing the `<img>` elem.

Come to think of it, we don't need those lines and should replace them with sizing of the `<svg>` element directly.

**Comment by erroronline1** [comment]
ah, yes! thank you. will be part of my next push if you don't mind.
