### ISSUE TITLE
Horizontal overflow

### ISSUE THREAD

**Issue by ModisR** [Mightyfrong/gallifreyan-translation-helper#30]
Haven't tested on other browsers but on Firefox, there is a horizontal scroll bar even when the window is wide enough to fit all the page content.

**Comment by erroronline1** [comment]
yes. chrome and unsurprisingly chromium edge as well. not on firefox and chrome mobile though. i guess it's the shadow, wasn't aware that it has scroll-space properties. it was a replacement for the svg-glow of the header to unify the design for responsive mode but save some space by not displaying the head-piece image.

duckduckgo does not scroll as wel, but has issues with the myselect instead.

**Comment by erroronline1** [comment]
added `overflow-x: hidden` to the body. the content is supposed to be responsible and rendered images that exceed the viewport width are shrunken by default. feel free to reopen this issue if this leads to problems.
